from __future__ import annotations


SCHEDULER_JOB_SPECS = (
    {
        "id": "sync_gsc_all_projects",
        "scheduler_id": "gsc_sync",
        "name": "GSC 排名同步",
        "schedule": "每日 03:00",
        "icon": "📊",
        "callable_name": "sync_gsc_all_projects",
        "trigger_type": "cron",
        "trigger_kwargs": {"hour": 3, "minute": 0},
        "admin_visible": True,
    },
    {
        "id": "sync_ga4_all_projects",
        "scheduler_id": "ga4_sync",
        "name": "GA4 頁面指標",
        "schedule": "每日 03:30",
        "icon": "📈",
        "callable_name": "sync_ga4_all_projects",
        "trigger_type": "cron",
        "trigger_kwargs": {"hour": 3, "minute": 30},
        "admin_visible": True,
    },
    {
        "id": "sync_keyword_trends",
        "scheduler_id": "trends_sync",
        "name": "關鍵字趨勢同步",
        "schedule": "每月 1 號 03:45",
        "icon": "📈",
        "callable_name": "sync_keyword_trends",
        "trigger_type": "cron",
        "trigger_kwargs": {"day": 1, "hour": 3, "minute": 45},
        "admin_visible": True,
    },
    {
        "id": "sync_gbp_metrics",
        "scheduler_id": "gbp_sync",
        "name": "GBP 指標同步",
        "schedule": "每日 03:50",
        "icon": "🏪",
        "callable_name": "sync_gbp_metrics",
        "trigger_type": "cron",
        "trigger_kwargs": {"hour": 3, "minute": 50},
        "admin_visible": False,
    },
    {
        "id": "backfill_action_outcomes",
        "scheduler_id": "outcome_backfill",
        "name": "行動成效回填",
        "schedule": "每日 04:00",
        "icon": "🎯",
        "callable_name": "backfill_action_outcomes",
        "trigger_type": "cron",
        "trigger_kwargs": {"hour": 4, "minute": 0},
        "admin_visible": True,
    },
    {
        "id": "check_scheduled_publishes",
        "scheduler_id": "sched_publish",
        "name": "定時發佈檢查",
        "schedule": "每日 04:05",
        "icon": "🗓️",
        "callable_name": "check_scheduled_publishes",
        "trigger_type": "cron",
        "trigger_kwargs": {"hour": 4, "minute": 5},
        "admin_visible": True,
    },
    {
        "id": "check_published_noindex",
        "scheduler_id": "publish_verify",
        "name": "已發布頁驗證",
        "schedule": "每日 04:10",
        "icon": "🛡️",
        "callable_name": "check_published_noindex",
        "trigger_type": "cron",
        "trigger_kwargs": {"hour": 4, "minute": 10},
        "admin_visible": False,
    },
    {
        "id": "persist_operations_health_snapshot",
        "scheduler_id": "operations_snapshot",
        "name": "營運健康快照",
        "schedule": "每日 04:20",
        "icon": "🩺",
        "callable_name": "persist_operations_health_snapshot",
        "trigger_type": "cron",
        "trigger_kwargs": {"hour": 4, "minute": 20},
        "admin_visible": True,
    },
    {
        "id": "run_competitor_serp_check",
        "scheduler_id": "competitor_serp",
        "name": "競品 SERP 追蹤",
        "schedule": "每週一 04:30",
        "icon": "🔍",
        "callable_name": "run_competitor_serp_check",
        "trigger_type": "cron",
        "trigger_kwargs": {"day_of_week": "mon", "hour": 4, "minute": 30},
        "admin_visible": True,
    },
    {
        "id": "check_gsc_sitemap_health",
        "scheduler_id": "sitemap_health",
        "name": "Sitemap 健康檢查",
        "schedule": "每週一 04:45",
        "icon": "🗺️",
        "callable_name": "check_gsc_sitemap_health",
        "trigger_type": "cron",
        "trigger_kwargs": {"day_of_week": "mon", "hour": 4, "minute": 45},
        "admin_visible": False,
    },
    {
        "id": "run_attribution_engine",
        "scheduler_id": "attribution",
        "name": "成效歸因分析",
        "schedule": "每週一 05:00",
        "icon": "🧮",
        "callable_name": "run_attribution_engine",
        "trigger_type": "cron",
        "trigger_kwargs": {"day_of_week": "mon", "hour": 5, "minute": 0},
        "admin_visible": True,
    },
    {
        "id": "check_refresh_triggers",
        "scheduler_id": "refresh_check",
        "name": "內容更新檢查",
        "schedule": "每週二 04:00",
        "icon": "🔄",
        "callable_name": "check_refresh_triggers",
        "trigger_type": "cron",
        "trigger_kwargs": {"day_of_week": "tue", "hour": 4, "minute": 0},
        "admin_visible": True,
    },
    {
        "id": "sync_backlink_metrics",
        "scheduler_id": "backlink_sync",
        "name": "反向連結同步",
        "schedule": "每週二 05:30",
        "icon": "🔗",
        "callable_name": "sync_backlink_metrics",
        "trigger_type": "cron",
        "trigger_kwargs": {"day_of_week": "tue", "hour": 5, "minute": 30},
        "admin_visible": False,
    },
    {
        "id": "check_ranking_drops",
        "scheduler_id": "ranking_drops",
        "name": "排名掉落偵測",
        "schedule": "每週三 06:00",
        "icon": "📉",
        "callable_name": "check_ranking_drops",
        "trigger_type": "cron",
        "trigger_kwargs": {"day_of_week": "wed", "hour": 6, "minute": 0},
        "admin_visible": True,
    },
    {
        "id": "run_index_coverage_check",
        "scheduler_id": "index_coverage",
        "name": "Index Coverage 檢查",
        "schedule": "每週五 05:00",
        "icon": "📚",
        "callable_name": "run_index_coverage_check",
        "trigger_type": "cron",
        "trigger_kwargs": {"day_of_week": "fri", "hour": 5, "minute": 0},
        "admin_visible": False,
    },
    {
        "id": "run_l1_pattern_analysis",
        "scheduler_id": "l1_learn",
        "name": "L1 模式學習",
        "schedule": "每月 1 號 06:00",
        "icon": "🔬",
        "callable_name": "run_l1_pattern_analysis",
        "trigger_type": "cron",
        "trigger_kwargs": {"day": 1, "hour": 6, "minute": 0},
        "admin_visible": True,
    },
    {
        "id": "run_l2_roi_analysis",
        "scheduler_id": "l2_learn",
        "name": "L2 ROI 分析",
        "schedule": "每月 1 號 07:00",
        "icon": "💰",
        "callable_name": "run_l2_roi_analysis",
        "trigger_type": "cron",
        "trigger_kwargs": {"day": 1, "hour": 7, "minute": 0},
        "admin_visible": True,
    },
    {
        "id": "run_auto_pipeline",
        "scheduler_id": "auto_pipeline",
        "name": "自動 AI Pipeline",
        "schedule": "每日 08:00",
        "icon": "🤖",
        "callable_name": "run_auto_pipeline",
        "trigger_type": "cron",
        "trigger_kwargs": {"hour": 8, "minute": 0},
        "admin_visible": True,
    },
    {
        "id": "run_weekly_reflection",
        "scheduler_id": "weekly_reflection",
        "name": "週級反思學習",
        "schedule": "每週日 08:00",
        "icon": "🧠",
        "callable_name": "run_weekly_reflection",
        "trigger_type": "cron",
        "trigger_kwargs": {"day_of_week": "sun", "hour": 8, "minute": 0},
        "admin_visible": True,
    },
    {
        "id": "send_weekly_report",
        "scheduler_id": "weekly_report",
        "name": "週報推送",
        "schedule": "每週日 09:00",
        "icon": "📬",
        "callable_name": "send_weekly_report",
        "trigger_type": "cron",
        "trigger_kwargs": {"day_of_week": "sun", "hour": 9, "minute": 0},
        "admin_visible": True,
    },
    {
        "id": "run_render_verification",
        "scheduler_id": "render_verify",
        "name": "前台 Render 驗證",
        "schedule": "每日 10:00",
        "icon": "🧪",
        "callable_name": "run_render_verification",
        "trigger_type": "cron",
        "trigger_kwargs": {"hour": 10, "minute": 0},
        "admin_visible": True,
    },
    {
        "id": "_scheduler_heartbeat_job",
        "scheduler_id": "scheduler_heartbeat",
        "name": "Scheduler Heartbeat",
        "schedule": "每分鐘",
        "icon": "💓",
        "callable_name": "_scheduler_heartbeat_job",
        "trigger_type": "interval",
        "trigger_kwargs": {"minutes": 1},
        "admin_visible": False,
    },
)